<script setup>
import { computed, reactive, ref } from 'vue'
import { Delete, Edit, Plus, Search } from '@element-plus/icons-vue'
const query=reactive({keyword:'',state:''}); const selected=ref([]); const dialog=ref(false); const editing=reactive({title:'',categoryId:'',state:'草稿',content:''})
const rows=ref([{id:1,title:'Vue 3 组合式 API 入门',category:'前端开发',state:'已发布',time:'2026-08-26'},{id:2,title:'Spring Boot 项目部署笔记',category:'后端开发',state:'草稿',time:'2026-08-25'},{id:3,title:'接口鉴权与 JWT 实践',category:'后端开发',state:'已发布',time:'2026-08-23'}])
const filtered=computed(()=>rows.value.filter(x=>(!query.keyword||x.title.includes(query.keyword))&&(!query.state||x.state===query.state)))
function edit(row){Object.assign(editing,row);dialog.value=true} function add(){Object.assign(editing,{title:'',categoryId:'',state:'草稿',content:''});dialog.value=true} function remove(){rows.value=rows.value.filter(x=>!selected.value.includes(x));selected.value=[]} function save(){dialog.value=false}
</script>
<template><section class="page-panel glass"><div class="page-heading"><div><h2>文章管理</h2><p>查看、筛选和维护文章内容</p></div><el-button type="primary" :icon="Plus" @click="add">新增文章</el-button></div><div class="toolbar"><el-input v-model="query.keyword" :prefix-icon="Search" placeholder="搜索文章标题" clearable/><el-select v-model="query.state" placeholder="文章状态" clearable><el-option label="已发布" value="已发布"/><el-option label="草稿" value="草稿"/></el-select><el-button :icon="Delete" :disabled="!selected.length" @click="remove">删除选中</el-button></div><div class="table-wrap"><el-table :data="filtered" @selection-change="selected=$event" style="width:100%"><el-table-column type="selection" width="48"/><el-table-column prop="title" label="标题" min-width="240"/><el-table-column prop="category" label="分类" width="140"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.state==='已发布'?'success':'info'">{{row.state}}</el-tag></template></el-table-column><el-table-column prop="time" label="更新时间" width="130"/><el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-tooltip content="编辑"><el-button text :icon="Edit" @click="edit(row)"/></el-tooltip></template></el-table-column></el-table></div><div class="pagination"><el-pagination background layout="prev, pager, next" :total="filtered.length"/></div><el-dialog v-model="dialog" :title="editing.id?'编辑文章':'新增文章'" width="600px"><el-form label-width="70px"><el-form-item label="标题"><el-input v-model="editing.title"/></el-form-item><el-form-item label="分类"><el-select v-model="editing.categoryId" placeholder="选择分类"><el-option label="前端开发" value="1"/><el-option label="后端开发" value="2"/></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="editing.state"><el-radio value="草稿">草稿</el-radio><el-radio value="已发布">发布</el-radio></el-radio-group></el-form-item><el-form-item label="内容"><el-input v-model="editing.content" type="textarea" :rows="5"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
