<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Lock, User } from '@element-plus/icons-vue'
import http from '../api/http'
const router = useRouter(); const tab = ref('login'); const loading = ref(false)
const form = reactive({ username:'', password:'', old_pwd:'', new_pwd:'', re_pwd:'' })
async function submit() { loading.value = true; try { if (tab.value === 'login') { const token = await http.post('/user/login', null, { params:{ username:form.username, password:form.password } }); localStorage.setItem('token', token); localStorage.setItem('userName', form.username); ElMessage.success('登录成功'); router.push('/dashboard') } else if (tab.value === 'register') { await http.post('/user/register', null, { params:{ username:form.username, password:form.password } }); ElMessage.success('注册成功，请登录'); tab.value='login' } else { if (!localStorage.getItem('token')) return ElMessage.warning('修改密码需要先登录'); await http.patch('/user/updatePwd', { old_pwd:form.old_pwd, new_pwd:form.new_pwd, re_pwd:form.re_pwd }); ElMessage.success('密码已修改，请重新登录'); localStorage.removeItem('token'); tab.value='login' } } finally { loading.value = false } }
</script>
<template>
  <main class="login-page"><section class="login-copy"><div class="copy-inner"><span class="eyebrow">CONTENT WORKSPACE</span><h1>文章管理后台</h1><p>集中管理文章、分类与个人资料，让内容工作清晰有序。</p><div class="copy-line"><span></span>Vue 3 · Element Plus</div></div></section><section class="login-area"><div class="login-card"><div class="mobile-brand">Article Admin</div><h2>{{ tab === 'login' ? '欢迎回来' : tab === 'register' ? '创建账号' : '修改密码' }}</h2><p class="sub">{{ tab === 'login' ? '使用你的账号继续' : '完善信息后即可继续操作' }}</p><el-tabs v-model="tab" stretch><el-tab-pane label="登录" name="login"/><el-tab-pane label="注册" name="register"/><el-tab-pane label="修改密码" name="password"/></el-tabs><el-form @submit.prevent="submit"><el-form-item v-if="tab !== 'password'"><el-input v-model="form.username" size="large" placeholder="用户名" :prefix-icon="User"/></el-form-item><el-form-item v-if="tab !== 'password'"><el-input v-model="form.password" size="large" type="password" show-password placeholder="密码" :prefix-icon="Lock"/></el-form-item><template v-else><el-form-item><el-input v-model="form.old_pwd" type="password" show-password placeholder="原密码" :prefix-icon="Lock"/></el-form-item><el-form-item><el-input v-model="form.new_pwd" type="password" show-password placeholder="新密码" :prefix-icon="Lock"/></el-form-item><el-form-item><el-input v-model="form.re_pwd" type="password" show-password placeholder="确认新密码" :prefix-icon="Lock"/></el-form-item></template><el-button native-type="submit" type="primary" size="large" :loading="loading" class="submit">{{ tab === 'login' ? '登录' : tab === 'register' ? '注册账号' : '确认修改' }}</el-button></el-form></div></section></main>
</template>
<style scoped>
.login-page{min-height:100vh;display:grid;grid-template-columns:1.1fr .9fr;background:#eff6f7}.login-copy{background:#0d7d70;color:#f4fffd;position:relative;overflow:hidden}.login-copy:after{content:"";position:absolute;width:520px;height:520px;border:1px solid rgba(255,255,255,.18);border-radius:50%;right:-210px;bottom:-250px}.copy-inner{max-width:460px;margin:0 auto;padding:20vh 36px}.eyebrow{font-size:12px;font-weight:700;opacity:.75}.copy-inner h1{font-size:42px;margin:18px 0;letter-spacing:0}.copy-inner p{font-size:17px;line-height:1.8;opacity:.82}.copy-line{margin-top:70px;display:flex;gap:10px;align-items:center;font-size:13px;opacity:.76}.copy-line span{width:34px;border-top:1px solid}.login-area{display:grid;place-items:center;padding:26px}.login-card{width:min(390px,100%);padding:10px}.login-card h2{font-size:28px;margin:22px 0 8px}.sub{color:#68778a;margin:0 0 22px}.submit{width:100%;margin-top:8px}.mobile-brand{display:none;color:#0d7d70;font-weight:750}.login-card :deep(.el-tabs__item){font-size:14px}@media(max-width:800px){.login-page{grid-template-columns:1fr}.login-copy{display:none}.mobile-brand{display:block}.login-area{align-items:start;padding-top:12vh}}
</style>
